### ISSUE TITLE
Colorize 0.75 Behavior

### ISSUE THREAD

**Issue by metaskills** [fazibear/colorize#38]
I can not explain why, but after bundle updating to the latest colorize gem via konacha dependency, my test output is messed up. If I console into my Rails app using the different versions, here is what I see.

```ruby
# 0.7.3
>> "Ken".colorize(:green)
=> "\e[0;32;49mKen\e[0m"

# 0.7.5
>> "Ken".colorize(:green)
=> "\e[greenmKen\e[0m"
```

However, if I just start an irb session and load the 0.7.5 colorize gem, all is fine. Do you have any ideas what would cause the discrepancy. There are no other gems that have a colorize method. Could there be something in this 0.7.5 release that has some non-deterministic behavior based on load order? TIA for your time.

**Comment by fazibear** [comment]
Its really weird. 
Check with just bundler, created empty rails app, checked both version and everything is fine. 
Checked also rails app with konacha gem. Budler installed 0.7.5. And everything look fine.
