### ISSUE TITLE
TypeError: no implicit conversion of Symbol into String. Ruby 2.2.2

### ISSUE THREAD

**Issue by dimoon** [fazibear/colorize#42]
```
puts "This is blue".colorize(:red)
TypeError: no implicit conversion of Symbol into String
	from /home/dimoon/.rvm/gems/ruby-2.2.2/gems/colored-1.2/lib/colored.rb:70:in `colorize'
```
```
String.color_samples
TypeError: no implicit conversion of Hash into String
	from /home/dimoon/.rvm/gems/ruby-2.2.2/gems/colored-1.2/lib/colored.rb:70:in `colorize'
```

**Comment by fazibear** [comment]
This is `colored` gem, not `colorize`.

**Comment by nickaknudson** [comment]
For anyone else experiencing this error: `colored` and `colorize`are incompatible with each other. Check that you are not using both gems simultaneously AND that none of your dependencies have the other as a dependency.

I experienced this error after one of my dependencies had `colored` as a dependency and I tried to use `colorize`.
