### ISSUE TITLE
Relicense under the LGPL or MIT?

### ISSUE THREAD

**Issue by connorshea** [fazibear/colorize#47]
Hey @fazibear, I'm working on verifying license compliance for [GitLab](https://about.gitlab.com) right now and we use your gem in our application. You can see [the relevant issue and discussion here](https://gitlab.com/gitlab-com/operations/issues/164).

Essentially, GitLab CE is licensed under the MIT Expat. We can't use a GPL'd gem without the application itself becoming GPL. Your gem and one other (which we're replacing) are the only things stopping us from ensuring compliance at the moment. Right now we have two options: replace/remove the gem or have the gem be relicensed.

Browsing through some of your other libraries, the newer ones seem to all be MIT, so that's definitely an option. Alternatively, you can use [the LGPL](http://choosealicense.com/licenses/lgpl-3.0/) if you'd like to keep the constraints of the GPL with the caveat that non-GPL applications can still link to the gem (assuming it's unmodified) without having to be GPL themselves.

The process of *should* be relatively simple. Since there are 9 contributors to the library, you'll need to get each of them to agree to relicense the code they've contributed (assuming it's still in the library and hasn't been replaced). [You can read about Dolphin doing something like this (albeit at a much larger scale) here](https://dolphin-emu.org/blog/2015/05/25/relicensing-dolphin/).

My understanding is that, for trivial contributions (e.g. only deleting code, not adding code, or just fixing spelling/grammar) they don't own copyright over any of the code, so you don't need them to agree. So that should cover [AJ-Acevedo](https://github.com/fazibear/colorize/commit/99569315ba98436702255430f57030f602ca39ad), [josegonzalez](https://github.com/fazibear/colorize/commit/1b412654035ca805af8e4d76248f0b4a3318e6d3), [adie](https://github.com/fazibear/colorize/commit/94d77b704325c75ee13052533f557ed342a9b3fc), [damphyr](https://github.com/fazibear/colorize/commit/1a255925153f3a7a74fd676f7d71c45b9ae73138), and [Rakoth](https://github.com/fazibear/colorize/commit/556e9d2238c8fbe5a510d6abecf7098bb7e3f59f). 

We'd need permission from satyap, you (fazibear), namusyaka, and frozzare (I won't `@mention` them so as not to bother them with notifications if you're uninterested in relicensing. If you are, we can notify them so they can comment).

If you're interested in doing this, we'd be happy to help if we can. If not, that's perfectly fine, we'd just like to know so we can move to another gem.

Best and thank you for your time,
Connor Shea

**Comment by connorshea** [comment]
As an aside, since your gem [has been downloaded more than 7 million times](https://rubygems.org/gems/colorize), every application using the gem for which source code is distributed is currently not complying with the GPL if their application is not licensed under the GPL. So, that's probably quite a few applications.

I don't know if you intended for that, but I wanted to point it out. If we were the only ones using it, I probably wouldn't have bothered opening this :)

**Comment by connorshea** [comment]
Bumping, sorry to be a bother, just wanted to make sure this was noticed.

**Comment by sschuberth** [comment]
@connorshea Meanwhile, you may want to consider using this MIT-licensed alternative (using the Strinhg mixin approach): https://github.com/sickill/rainbow

**Comment by connorshea** [comment]
@sschuberth thanks, I've been looking at alternatives since this issue hasn't seen any activity. Rainbow is looking like the solution we'll probably go with.

**Comment by fazibear** [comment]
I guess problem is solved for your application.

**Comment by sschuberth** [comment]
@fazibear It's more like a work-around. It still would be nice if you could comment on the request to re-license, i.e. if you're willing to do that or not.

**Comment by connorshea** [comment]
Anyone interested in replacing colorize with rainbow in their apps can see here for how we changed GitLab for it: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/4425
