### ISSUE TITLE
How to make only bold?

### ISSUE THREAD

**Issue by Paxa** [fazibear/colorize#50]
I try

`'test'.coloroze(:bold)` - no effect
`'test'.coloroze(:white).bold` - become bold

What is a right way to do it?

Probably it generates wrong codes, this code prints bold:

```ruby
puts "\033[1mSome Text"
```

**Comment by fazibear** [comment]
<img width="316" alt="screen shot 2016-08-12 at 19 11 47" src="https://cloud.githubusercontent.com/assets/687/17630701/a51e3634-60c0-11e6-8ef8-045fa2ecb51c.png">
Weird. As you can see, for me it works just fine. Maybe you have weird terminal settings, like `make bright colors bold` ?
