### ISSUE TITLE
Consider adding support for random and sequenced colours

### ISSUE THREAD

**Issue by Bodacious** [fazibear/colorize#58]
It would be great if we could set a colorized string without having to specify the colour.

Something like:

    puts "hello world".colorize(:random)

and 

    puts "hello world".colorize(:next)

I've added this to my own application as a quick hack

    module ColorStepper

      COLOURS = [:red, :light_red, :green, :light_green, :yellow, :light_yellow, :blue, :light_blue, :magenta, :light_magenta, :cyan, :light_cyan, :white, :light_white]
  
      module_function
  
      def enumerator
        @enumerator ||= COLOURS.each
      end
  
      def next
        begin
          enumerator.next
        rescue 
          enumerator.rewind
          retry
        end
      end
      
      def random
        COLOURS.sample
      end
  
    end

**Comment by fazibear** [comment]
I don't see the point of that. It's really easy to set random colors.
```ruby
def random_color
  ColorizedString.colors.sample
end

puts "hello world".colorize(random_color)
```
I guess that there are very specific cases for something like this.There is no need to implement that stuff in lib. 

Thanks for idea.
