### ISSUE TITLE
Incompatible with colored gem

### ISSUE THREAD

**Issue by vishnun** [fazibear/colorize#60]
The gem uses `colorize` method which is incompatible with the **colored** gem. Colorize is used by **Konacha** gem for javascript tests in headless mode. It'll be great if you can work something out with the developers of that gem.

**Comment by fazibear** [comment]
There is two way to use `colorize`. First one is with `require 'colorize'` that extends `String` class, or by using `require 'colorized_string'` that don't. The second one should not conflict to other gems.

BTW `colored` gem in inactive for 8 years.

**Comment by vishnun** [comment]
That's great. Now I just have to fix it in Kanocha and ask them to accept my pull request once i'm done.
Thanks a lot.
And yeah, `colored` gem is old but it's still a dependency for a few gems that we use in our project. 

Thanks for responding.
