### ISSUE TITLE
Question - Is it possible to strip the color codes from a string that is read from STDIN

### ISSUE THREAD

**Issue by avnerbarr** [fazibear/colorize#64]
I am using the library to colorize logs and it works great.

In other cases though I am reading logs from stdin through a pipe, and would like to strip the existing color codes and then parse the lines and then recolor and then print to stdout.

For example :
```
some_process_which_creates_colored_logs | another_process_which_reads_from_STDIN_the_colorized_log.rb`
```

and then:
```
another_process_which_reads_from_STDIN_the_colorized_log.rb
STDIN.each_line do |line|
  clean_line = line.strip_color_code_if_exists
  printer.print(clean_line.yellow) 
end
```

**Comment by fazibear** [comment]
Of course it's possible.

![use_the_google_luke](https://user-images.githubusercontent.com/687/34174743-492d21a4-e4fa-11e7-81d5-d78f73d330f1.jpg)
