### ISSUE TITLE
Rainbow option (Feature Request)

### ISSUE THREAD

**Issue by elisaado** [fazibear/colorize#65]
I'd like an option to rainbow-ize strings

Thanks

**Comment by GitHubUserCDC** [comment]
oh please do it 👍

**Comment by MarchandMD** [comment]
I further encourage the more general support for traditional color hue spectrum: ROYGBIV

**Comment by jknight1725** [comment]
```
class String
  def rainbow
    rainbow_colors = %i[red light_red light_yellow green light_green light_blue blue light_magenta]
    r = rainbow_colors.each.cycle
    each_char.map { |c| c.send(r.next) }
  end
end

text = 'Colorize me!, color me like a rainbow!'.rainbow.join
puts text
```

**Comment by jefflunt** [comment]
That's a lot of extra hidden characters in text. Fun idea though! 

IMO something like this goes a little bit beyond the intent of what this gem would do: making simple color enhancements and highlights.

I know it's been 2-3 years, but would you be at all interested in submitting a PR, even for a very minimal possible implementation for this? This library isn't all that big.

Alternatively I could see a rainbow as either (a) something you need to explicitly enable, or (b) as a separate gem, something like `colorize-rainbow` that would follow a similar mechanism as this library (i.e. extending the `String` class) to add this functionality.

Thoughts @elisaado ?

BTW: I'm not a library maintainer, and even if a PR were submitted for this, I can't say if @fazibear would be open to it, but at least with a proposed solution there's greater ground for possible feedback.

Thanks!

**Comment by jefflunt** [comment]
Also, if this is the only feature you're particularly interested in, consider the [`rainbow`](https://rubygems.org/gems/rainbow) or [`lolize`](https://rubygems.org/gems/lolize) gems.

[Here's a blog post](https://medium.com/@kyleconlon13/ruby-colorful-code-runs-better-its-cyantifically-proven-2826e016d9bb) that shows some visual differences in their features.

**Comment by fazibear** [comment]
Looks like [lolize](https://rubygems.org/gems/lolize) gem it the best thing for rainbowing text :)
