### ISSUE TITLE
Gem project release notes or status

### ISSUE THREAD

**Issue by hlascelles** [fazibear/colorize#74]
@fazibear thank you for this excellent gem. It has been a mainstay in the ruby community and used by thousands of companies and projects. It is still being added as a dependency to new gems that are coming out now.

I see there hasn't been a release in a few years. This may be because that it is considered "feature complete", and no further releases are planned. 

If so, can we put something at the top of the README to say something to that effect? Otherwise more PRs (which may take [hours](https://github.com/fazibear/colorize/issues/71#issuecomment-1007197937)) may be opened which will never be used. Maybe a pointer to other gems in this space that are accepting changes (eg [rainbow](https://github.com/sickill/rainbow) I believe).

Thanks again!

**Comment by fazibear** [comment]
I'm still maintaining it!

**Comment by hlascelles** [comment]
:fireworks: :man_dancing:
