### ISSUE TITLE
Readline support issue (should be optional ?)

### ISSUE THREAD

**Issue by jules-w2** [fazibear/colorize#94]
Hey  @fazibear 

On your commit  9aa70380e3f8f49d71fd0f16822fcba3b8bdc1e7 [9aa7038],
you added support for readline, but that should be optional... i lost all my colors in the rail loggers..

I try to do it but it's not working...

```ruby
#instance_methods.rb

def colorize(params)
  return self if self.class.disable_colorization

  scan_for_colors.inject(self.class.new) do |str, match|
    colors_from_params(match, params)
    defaults_colors(match)
    str << "(\001)?\033[#{match[0]};#{match[1]};#{match[2]}m(\002)?#{match[3]}(\001)?\033[0m(\002)?"
  end
end

......

def scan_for_colors
scan(/(\001)?\033\[([0-9;]+)m(\002)?(.+?)(\001)?\033\[0m(\002)?|([^(\001)?\033]+)/m).map do |match|
    split_colors(match)
 end
end
```

before this commit
<img width="2056" alt="Screenshot 2023-06-19 at 12 17 40" src="https://github.com/fazibear/colorize/assets/2778700/424edef5-8864-4abc-88f8-b04c3d53e3be">

after this commit
<img width="2056" alt="Screenshot 2023-06-19 at 12 18 44" src="https://github.com/fazibear/colorize/assets/2778700/dea79aeb-0f8c-471d-bd07-cdfd8cc0dd17">

Do yoy have any solutions to fix it?

Bests

**Comment by fazibear** [comment]
Hey @jules-w2 your solution will break code. You're adding more regex groups.

if `"test".blue.red` give you red (for me is working) those regexes works correctly.  Will take a look closely.

**Comment by fazibear** [comment]
Hey @jules-w2 Could you check if #95 works for you?

**Comment by jules-w2** [comment]
thanks 👍 it works again with this fix
