### ISSUE TITLE
Class ColorizedString add grey alias twice

### ISSUE THREAD

**Issue by Guistoff081** [fazibear/colorize#96]
there's a duplicate method  call `add_color_alias(:grey, :light_black)`, when it is called on `class ColorizedString` this results on an error caused by `check_if_color_available! ` "Colorize: color named :grey already exist!"

**Comment by fazibear** [comment]
@Guistoff081 Can you provide steps to reproduce?

**Comment by fazibear** [comment]
Can you check if #97 helps?

**Comment by Guistoff081** [comment]
Yeah it did solve my problem! Thank you for the fast response, i almost ended up building my own solution XD

**Comment by fazibear** [comment]
`v1.0.2` released :)
