### ISSUE TITLE
Regressions

### ISSUE THREAD

**Issue by akimd** [fazibear/colorize#99]
Hi,

With the latest release, there are unexpected changes.  

One was the removal of the question marks, recently fixed.

A second one is that `String#magenta` is no longer supported (and it was not advertised in the release notes).

And finally, I don't know what was the impetus to change the escape sequences, but they are not recognize by `less`, and now I get

```
^A^Bmy-message^A^B
```

displayed where, before the recent release, everything was displayed correctly.  Just try `ruby -e "require 'colorize'; puts 'foo'.magenta" | less -R` to see the problem (or some other color if magenta does not work ;-).

The changes for readline (whose purple^H^Hoses are not entirely clear to me) seem to have many unexpected effects.  It should probably be opted-in rather than mandatory.

Cheers.

**Comment by fazibear** [comment]
@akimd Looks like it's a readline support problem. Created a PR to make it optional. Take a look please #100

**Comment by akimd** [comment]
Hi @fazibear,
I've read the PR, it looks right to me.  Thanks for this!

**Comment by fazibear** [comment]
Fixed #100
